#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

python spi/init.py

cp /var/www/html/spi/data/panorama.png /var/www/html/spi/img/panorama.png

exec "$@"
