version: '2'
services:
    db:
        image: mongo:latest
        volumes:
            - /opt/uav/db/data:/data/db
            - /opt/uav/db/conf:/data/configdb
        
    backend:
        image: solarapi:latest
        volumes:
            - /opt/uav/data:/usr/src/app/data
        environment:
            - IMG_ROOT=/usr/src/app/data
            - BG_PATH=/usr/src/app/bg
            - GSD_PANORAMA=5.3793
            - GSD_IR=1
            - MONGO_HOST=mongo
        links:
            - db:mongo
        ports:
            - "5000:5000"
    frontend:
        image: solarui:latest
        volumes:
            - /opt/uav/data:/var/www/html/data
        ports:
            - "8090:80"
        links:
            - db:mongo
            - backend:solarapi
