FROM jjanzic/docker-python3-opencv

MAINTAINER "Jason Jiao <jason.jiao@honeywell.com>"

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN wget https://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.61.tar.gz \
    && tar zfx Image-ExifTool-10.61.tar.gz \
    && cd Image-ExifTool-10.61 \
    && perl Makefile.PL \
    && make install \
    && rm -fr Image-ExifTool-10.61 

